### PR TITLE
fixup compiler issue

### PR DESCRIPTION
**Pull request by jamesadevine**
See https://github.com/microsoft/jacdac-stm32x0/pull/44

### CODE REVIEW

**Comment by jamesadevine** [comment]
@mmoskal There is a fundamental problem with the STATIC_ASSERT macro. If two asserts are on the same line in two different files, they end up emitting same-name enums which creates a compiler error.

The bodge is to just move one of the static asserts, but I wanted to check with you if there is a more permanent patch I can apply.

I tried to use __FILE__ to provide a unique identifier, however __FILE__ is a string and not a symbol/token (and therefore does not work with CONCAT)!

**Review by mmoskal — APPROVED** [review]
I wouldn't bother with PRs that just bump deps ;)

**Comment by mmoskal** [comment]
As for the static assert - maybe we can avoid them in header files? we could also pass an additional argument to STATIC_ASSERT that is added to the symbol name

**Comment by mmoskal** [comment]
I guess best to add STATIC_ASSERT_EXT with additional argument that we use when there is a conflict; it's somewhat hacky but less than moving lines

**Comment by jamesadevine** [comment]
> I wouldn't bother with PRs that just bump deps ;)

Ha, unless i misunderstand your meaning, i'm only using PRs to ensure that the build is good.

**Pull request merged**
