### PR TITLE
Flex sensor

### PR DESCRIPTION
**Pull request by jamesadevine**

### CODE REVIEW

**Review by mmoskal — APPROVED** [review]
Shouldn't we have a separate service for flex sensors? Or at least potentiometer variant? I guess it will do for now. cc @pelikhan

**Comment by pelikhan** [comment]
Definitely a variant.

**Comment by pelikhan** [comment]
potentiometer name seems more and more dodgy

**Comment by jamesadevine** [comment]
I have not flashed these boards yet, so there's still a chance to add the variant register. Updating all the sliders to have the variant register will be a challenge.

**Pull request merged**
