### PR TITLE
implement i2c_reset on lockup condition

### PR DESCRIPTION
**Pull request by jamesadevine**
Fix for https://github.com/microsoft/jacdac/issues/345

### CODE REVIEW

**Comment by jamesadevine** [comment]
requires: 

https://github.com/microsoft/jacdac-stm32x0/pull/21
https://github.com/microsoft/jacdac-c/pull/21

**Comment by mmoskal** [comment]
does the reset help? did you get a logic trace for the lockup? maybe we're doing something wrong?

**Comment by jamesadevine** [comment]
Will get a trace of the issue. I was under time constraints as I need to get things working reliably for EMC testing this week.

**Comment by jamesadevine** [comment]
Stale -- lock up was caused by reading sensor too frequently.

**Pull request closed without merging**
