### PR TITLE
Fix LED number for JM RGB LED BAR 10

### PR DESCRIPTION
**Pull request by Amerlander**
@pelikhan can you look at this?

### CODE REVIEW

**Comment by pelikhan** [comment]
@mmoskal

**Comment by mmoskal** [comment]
The module we built had 8 LEDs. Please follow the instructions here https://github.com/microsoft/jacdac-stm32x0/blob/main/README.md#adding-new-modules to add a new module with new product id, name, and number of LEDs.

**Comment by Amerlander** [comment]
Thank you. The 10 in the name was missleading me to think this device id always have 10 LED.

**Comment by pelikhan** [comment]
Thanks for reporting though! Yes 10 was the model number, not the number of LEDs !!!

**Pull request closed without merging**
