### PR TITLE
Rgb ring 

### PR DESCRIPTION
**Pull request by jamesadevine**
Add rgb ring

### CODE REVIEW

**Comment by jamesadevine** [comment]
RGB ring may require a different processor; flash size is too small. We could move to a simpler RGB LED service without animations for now? 

Thoughts @mmoskal ?

(P.S. need to remove the i2c_reset commit)

**Comment by jamesadevine** [comment]
let me break up servo dual and rgb_ring into two separate PRs

**Comment by jamesadevine** [comment]
Removed servo dual from this PR

**Comment by mmoskal** [comment]
you can use "Draft" PR instead of DONOTMERGE.

I'll see if we can save some bytes here and there

**Pull request closed without merging**
